name: lichen
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  camera: ^0.11.0+2             # Compatible with Dart 3.5.4
  image_picker: ^0.8.7+5        # Compatible and stable
  http: ^1.3.0
  geolocator: ^9.0.2 
  url_launcher: ^6.3.1
  webview_flutter: ^4.13.0# Compatible with Dart 3.5.4 and avoids toARGB32 issue

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0         # Compatible with Dart 3.5.4

flutter:
  uses-material-design: true
